name: 'Workflow Metrics'
description: 'Reports workflow metrics'
inputs:
  metrics-type:
    description: '"velocity" or "job_metrics" depending on the desired metrics to be collected'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install gems
      shell: bash
      run: |
        gem install octokit --silent
    - name: Export extra data
      shell: bash
      run: |
        if [ "${{ inputs.metrics-type }}" == "velocity" ]; then
          echo "PR_NUMBER=${{github.event.pull_request.number}}" >> $GITHUB_ENV
          echo "ACTION=${{github.event.action}}" >> $GITHUB_ENV
        else
          echo "ACTION=${{ inputs.metrics-type }}" >> $GITHUB_ENV
        fi
    - id: metric
      name: Calculate metrics
      shell: bash
      run: |
        ruby ${{ github.action_path }}/report_github_metrics.rb ${{github.repository}} ${{github.run_id}}
