name: main workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pretend these are real tests
        run: |
          sleep 30
          true
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pretend this is building stuff
        run: sleep 15

      - name: Pretend this is deploying stuff
        run: |
          date
          echo "Deploying the stuff"
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: ./.github/actions/metrics
        with:
          metrics-type: 'job_metrics'
        env:
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
